// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitChangelog
{
    internal sealed partial class Vsix
    {
        public const string Id = "GitChangelog.11b1e86f-4cf9-41a1-9a7e-c8bed4c9512d";
        public const string Name = "Git Changelog";
        public const string Description = @"Integrating changelog into git, but better";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "D_Inventor";
        public const string Tags = "";
    }
}
